# Generated by Django 5.0.3 on 2024-04-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_image_alter_facerecognition_record_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
        ),
    ]
